# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ea216ad1758753bf8a1064327cc7dc5178526ffd48acb1c3996f89feae4663a36aec2a3fd7c1ccf33fc68acd4f571efa3e8cd8e9de182b20a901f7253ff7bb8

test:
  secret_key_base: faa26ed11a2beba8c65ee1cd2e7c518affe3a9e3b3232907bc25b1d98eaed89ae049b49c219909046e0b83a646ee53fc387c905e21040845e0136321cdf0ac7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
